site_name: Keystone API
nav:
  - Introduction: index.md
  - Installation:
      - install/slurm.md
      - install/docker.md
      - install/systemd.md
  - Setup:
      - Application Settings: setup/settings.md
      - setup/notification.md
  - REST API:
      - api/openapi.md
      - api/authentication.md
      - api/filtering.md
      - api/logging.md
